DROP DATABASE IF EXISTS photos;

CREATE DATABASE photos;

USE photos;

CREATE TABLE restaurants (
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(55)
);

CREATE TABLE yelpusers (
  user_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data json NOT NULL
);

CREATE TABLE pictures (
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  url varchar(80) NOT NULL,
  postdate varchar(30),
  caption varchar(100),
  user int NOT NULL,
  restaurant int NOT NULL,
  FOREIGN KEY (user) REFERENCES users(user_id),
  FOREIGN KEY (restaurant) REFERENCES restaurants(id)
);
